### ISSUE TITLE
Ruby 2.7 support

### ISSUE THREAD

**Issue by scorbin-ewi** [jperelli/Redmine-Periodic-Task#106]
I have redmine installed on Debian buster and I am being held back from updating to the newest available version of ruby which is 2.7.  Error messages indicate that this plugin requires >=ruby2.3 <ruby2.7.  Are there plans to test on 2.7?  Love the plugin but cannot hold back updates too much longer in our environment.

**Comment by jperelli** [comment]
I'm using now ruby 3.2.3 for development. Please update to the latest version of the plugin v5.0.0
