### ISSUE TITLE
Redmine 4.2.3.stable failed to install, is it incompatible with this version?

### ISSUE THREAD

**Issue by shencangsheng** [jperelli/Redmine-Periodic-Task#109]
Redmine 4.2.3.stable failed to install, is it incompatible with this version?

**Comment by yzzy** [comment]
I guess it should be compatible.
What error do you get?
Please provide Redmine information too.

**Comment by shencangsheng** [comment]
@yzzy Installed successfully because of project name problems

**Comment by ashrafalzyoud** [comment]
@yzzy any update?!

**Comment by yzzy** [comment]
This issue was closed as completed by author, so plugin is compatible with the specified version.
