### ISSUE TITLE
Support for Redmine 5.0

### ISSUE THREAD

**Issue by broberts-dev** [jperelli/Redmine-Periodic-Task#111]
I'm inquiring about the plug-in's support for later versions, especially 5.0, of Redmine.  Redmine 5.0 was release about a month ago. Is it supported? If not, is there an upcoming release that is expected to support it? If so, what is that release and when is it expected?

* https://www.redmine.org/news/135
* https://www.redmine.org/projects/redmine/wiki/Changelog_5_0

**Comment by ashrafalzyoud** [comment]
Any update 5.0?!?
And I'm see many pull requests 
Can u check it

**Comment by ashrafalzyoud** [comment]
@jperelli

**Comment by jperelli** [comment]
Hi @ashrafalzyoud and @broberts-dev please try the new version 5.0.0 of this plugin, it should be compatible now with redmine v5. Reopen the ticket if you still have issues.
