### ISSUE TITLE
periodictasks is not working redmine:4.2.10

### ISSUE THREAD

**Issue by opino** [jperelli/Redmine-Periodic-Task#114]
do you have some sugestions what i can try?
<code>
root@f1a533fdd9cf:/usr/src/redmine# /usr/local/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production"
W, [2023-09-26T17:24:00.690706 #105]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-09-26T17:24:00.737876 #105]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-09-26T17:24:00.745167 #105]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
rake aborted!
Psych::DisallowedClass: Tried to load unspecified class: Set
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/coders/yaml_column.rb:51:in `yaml_load'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/coders/yaml_column.rb:26:in `load'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/type/serialized.rb:22:in `deserialize'
/usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/attribute.rb:165:in `type_cast'
/usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/attribute.rb:42:in `value'
/usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/attribute_set.rb:48:in `fetch_value'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/attribute_methods/read.rb:77:in `_read_attribute'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/attribute_methods/read.rb:40:in `__temp__36573747f6d6f5669656c646f56716c6575637'
/usr/src/redmine/plugins/periodictask/app/models/periodictask.rb:92:in `fill_custom_fields'
/usr/src/redmine/plugins/periodictask/app/models/periodictask.rb:56:in `generate_issue'
/usr/src/redmine/plugins/periodictask/lib/scheduled_tasks_checker.rb:9:in `block in checktasks!'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'
/usr/src/redmine/plugins/periodictask/lib/scheduled_tasks_checker.rb:4:in `checktasks!'
/usr/src/redmine/plugins/periodictask/lib/tasks/periodictask.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:check_periodictasks
(See full trace by running task with --trace)
root@f1a533fdd9cf:/usr/src/redmine# /usr/local/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production"
W, [2023-09-26T17:24:40.973979 #108]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-09-26T17:24:41.017125 #108]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-09-26T17:24:41.021973 #108]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
rake aborted!
Psych::DisallowedClass: Tried to load unspecified class: Set
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/coders/yaml_column.rb:51:in `yaml_load'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/coders/yaml_column.rb:26:in `load'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/type/serialized.rb:22:in `deserialize'
/usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/attribute.rb:165:in `type_cast'
/usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/attribute.rb:42:in `value'
/usr/local/bundle/gems/activemodel-5.2.8.1/lib/active_model/attribute_set.rb:48:in `fetch_value'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/attribute_methods/read.rb:77:in `_read_attribute'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/attribute_methods/read.rb:40:in `__temp__36573747f6d6f5669656c646f56716c6575637'
/usr/src/redmine/plugins/periodictask/app/models/periodictask.rb:92:in `fill_custom_fields'
/usr/src/redmine/plugins/periodictask/app/models/periodictask.rb:56:in `generate_issue'
/usr/src/redmine/plugins/periodictask/lib/scheduled_tasks_checker.rb:9:in `block in checktasks!'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'
/usr/src/redmine/plugins/periodictask/lib/scheduled_tasks_checker.rb:4:in `checktasks!'
/usr/src/redmine/plugins/periodictask/lib/tasks/periodictask.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:check_periodictasks
(See full trace by running task with --trace)
root@f1a533fdd9cf:/usr/src/redmine#
</code>

**Comment by yzzy** [comment]
Which Ruby version is used? For Redmine 4.2 you should use Ruby 2.7 at most.
https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Ruby-interpreter

**Comment by opino** [comment]
I am using redmine:4.2.10 with ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]

**Comment by yzzy** [comment]
At first sight seems like a bug in recent Redmine versions.
As a quick-and-dirty workaround you can patch `$REDMINE_ROOT/config/application.rb`
Before
```
    config.active_record.yaml_column_permitted_classes = [
      Date,
      Time,
      Symbol,
      ActiveSupport::HashWithIndifferentAccess,
      ActionController::Parameters
    ]
```
After
```
    config.active_record.yaml_column_permitted_classes = [
      Date,
      Time,
      Symbol,
      ActiveSupport::HashWithIndifferentAccess,
      ActionController::Parameters,
      Set
    ]
```
and restart Redmine

**Comment by R3vb3n** [comment]
Hi, i have also trouble: 
my System:   
  Redmine version                4.2.10.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  5.2.8.1
  Environment                    production
 periodictasks:                  4.1.0

plugin is shown in de administration-plugin overview and is also enabled in the specific project.
i also could create a perioci task but when i run the following command:

rake -f /opt/redmine/Rakefile redmine:check_periodictasks RAILS_ENV="production" --trace

the following "error" appears:
** Invoke redmine:check_periodictasks (first_time)
** Invoke environment (first_time)
** Execute environment
/var/lib/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/associations.rb:1855: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
/var/lib/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
** Execute redmine:check_periodictasks
/var/lib/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95: warning: The called method `select_all' is defined here
/var/lib/gems/2.7.0/gems/activemodel-5.2.8.1/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/activemodel-5.2.8.1/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here

on my view the task is executed, but no task is created. could someone help me

**Comment by yzzy** [comment]
Hi, officials said that Redmine 4.2 supports Ruby 2.7.2 and higher only https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Ruby-interpreter
I don't think that your issue may be solved by running recommended Ruby version but I guess you should try.

And when you run rake task maybe `production.log` has some hints what's going wrong.

**Comment by R3vb3n** [comment]
Thanks for the hint ;) i should upgrade the version. Perhaps this will also improve performance
Maybe i wrote my question to fast. I can confirm, that periodictasks run with my environment.
The periodictask was with some delay created.  1 1/2 h later.

**Comment by jperelli** [comment]
Thanks for the support @yzzy
