### ISSUE TITLE
Periodic task not working

### ISSUE THREAD

**Issue by Rickzuydam** [jperelli/Redmine-Periodic-Task#119]
Hello, I have an issue with the periodic task in Redmine. I'm using version 5.0.0, and now the periodic tasks are not showing up in Redmine. Do you have any tips for me?

Environment:
  Redmine version                5.0.0.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux-gnu]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Purplemine2-master (includes JavaScript)
SCM:
  Subversion                     1.13.0
  Mercurial                      5.3.1
  Cvs                            1.12.13
  Bazaar                         3.0.2
  Git                            2.36.0
  Filesystem                     
Redmine plugins:
  periodictask                   4.1.0
  redmine_checklists             3.1.21

**Comment by jperelli** [comment]
@Rickzuydam please try the new version 5.0.0 of this plugin, it should be compatible now with redmine v5. Please reopen the ticket if you still have issues.
