### ISSUE TITLE
Problem executing crontab in Bitnami distribution

### ISSUE THREAD

**Issue by SolverTwins** [jperelli/Redmine-Periodic-Task#120]
Hello I have an issue when I execute the crontab task.

>  * * * *  cd /opt/bitnami/redmine;/opt/bitnami/redmine/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production" >> prueba4.log 2>&1

If I execute manually its works perfect, 

> cd /opt/bitnami/redmine;/opt/bitnami/redmine/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production"

but when crontab start the task I have this error

> To install the version of bundler this project requires, run `gem install bundler -v '~> 2.5'`
> Activating bundler (~> 2.5) failed:
> Could not find 'bundler' (2.5.5) required by your /opt/bitnami/redmine/Gemfile.lock.
> To update to the latest version installed on your system, run `bundle update --bundler`.
> To install the missing version, run `gem install bundler:2.5.5`
> Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ru>
> 
> To install the version of bundler this project requires, run `gem install bundler -v '~> 2.5'`
>

**Comment by yzzy** [comment]
It seems your crontab task is running under _root_ user, not under _redmine_.
And BTW you have really old Ruby version.

**Comment by SolverTwins** [comment]
I dont understand, the bitnami distribution no use the redmine user, only  have the bitnami user, and when I execute the command fron the command line, its works,  how can I change the user to execute?

I Read that the crontab -e need to start in the root user no?.

Thanks  I have a little knowledge in ruby :(

**Comment by yzzy** [comment]
Do you mean docker bitnami distribution? At least the latest one has _redmine_ user. You can check who is the owner of _/opt/bitnami/redmine_ directory and its subdirs. Set this owner as _user-name_ in _/etc/crontab_

![Screenshot_20240531_131949](https://github.com/jperelli/Redmine-Periodic-Task/assets/390303/8080d4b5-b4fc-4d47-ac44-f66628719f84)

**Comment by SolverTwins** [comment]
Hello, THANK YOU for all your support, I have finally managed to get it working, the problem was very simple, you just need to add a complete path. I have created a sh file and added a path with the full path, and it works.

> 
> PATH=/opt/bitnami/apache/bin:/opt/bitnami/common/bin:/opt/bitnami/mariadb/bin:/opt/bitnami/mariadb/sbin:/opt/bitnami/rbenv/bin:/opt/bitnami/redmine/bin:/opt/bitnami/ruby/bin:/opt/bitnami/subversion/bin:/opt/bitnami/apache/bin:/opt/bitnami/common/bin:/opt/bitnami/mariadb/bin:/opt/bitnami/mariadb/sbin:/opt/bitnami/rbenv/bin:/opt/bitnami/redmine/bin:/opt/bitnami/ruby/bin:/opt/bitnami/subversion/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 
> cd /opt/bitnami/redmine
> /opt/bitnami/redmine/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production" >LogDefinitivo.log
> 

THANKS AGAIN

**Comment by SolverTwins** [comment]
THANKS
