### ISSUE TITLE
custom fields with "Required"

### ISSUE THREAD

**Issue by sergiobortsov** [jperelli/Redmine-Periodic-Task#16]
Periodictask does not create the issue in project there "Required" Custom fields applied. No errors in logs, just no issue after assigning. Please help how to fix it.

**Comment by sergiobortsov** [comment]
I'm not strong in ruby, but I think that its possible to add additional check in scheduled_task_checker.rb there
issue = Issue.new(:project_id=>task.project_id,  :tracker_id=>task.tracker_id, :assigned_to_id=>task.assigned_to_id, :author_id=>task.author_id, :subject=>task.subject, :description=>task.description);
If project uses the Required Custom field then add it during issue creation.
Is it possible?
I'll be grateful for any help with it.

**Comment by Sledav** [comment]
Hi.
For my instalaton I added a condition id scheduled_task_checker.rb
      if task.project_id == 2 and task.tracker_id == 6 then
		issue = Issue.new(:project_id=>task.project_id,  :tracker_id=>task.tracker_id, :category_id=>task.issue_category_id, :assigned_to_id=>task.assigned_to_id, :author_id=>task.author_id, :subject=>task.subject, :description=>task.description, :custom_field_values=>{"9"=>"ДИТ", "56"=>"Задачи вне плана", "54"=>"", "58"=>"", "60"=>"", "62"=>"", "65"=>"", "66"=>"", "67"=>"", "68"=>[""], "69"=>"0"})
	  elsif  task.project_id == 17 and task.tracker_id == 6 then
		issue = Issue.new(:project_id=>task.project_id,  :tracker_id=>task.tracker_id, :category_id=>task.issue_category_id, :assigned_to_id=>task.assigned_to_id, :author_id=>task.author_id, :subject=>task.subject, :description=>task.description, :custom_field_values=>{"9"=>"Бухгалтерия", "54"=>"", "64"=>"", "65"=>"", "66"=>"", "67"=>"Ломтева Ю.А."})
	  else
		issue = Issue.new(:project_id=>task.project_id,  :tracker_id=>task.tracker_id, :category_id=>task.issue_category_id, :assigned_to_id=>task.assigned_to_id, :author_id=>task.author_id, :subject=>task.subject, :description=>task.description);
      end

This is not the best solution, but it's work.
I think that the correct solution would be to create a new table "periodictasks_custom_fields". When creating a task to remember the values in this table. Table must have next columns:
-id;
-customized_id;
-custom_fiel_id;
-value.

I think it will be a universal solution. But I can not add custom fields to form " / app / views / periodictask / _form.html.erb "

**Comment by davidegiacometti** [comment]
Is anyone working on this? We need to manage a few mandatory custom fields.
I'd like to develop this but I am new to Rails. Any idea on how to implement this?

**Comment by jperelli** [comment]
Hi, I'm waiting for a pull request, if anyone wants to contribute.

**Comment by jperelli** [comment]
This should be working now! thanks @yzzy and @s-andy !
