### ISSUE TITLE
Close Ticket until a date and re-open it automaticly

### ISSUE THREAD

**Issue by JT1301** [jperelli/Redmine-Periodic-Task#30]
Hello,

maybe it is a cool and simple feature:
For example. You got a Ticket closed it but you need to do the same in maybe 2 weeks again.

It would be great if you can set this in the ticket to create a duplicate for the periodic-task.

**Comment by jperelli** [comment]
Well, this plugin works differently, It only creates a new issue without any reference to a previous issue. So it won't be possible to modify an already opened issue.

Maybe another plugin could do this, like this one https://github.com/edtsech/redmine_x_closed or a modification of that plugin.
