### ISSUE TITLE
README.md - wrong cron example

### ISSUE THREAD

**Issue by maxdevaine** [jperelli/Redmine-Periodic-Task#32]
Hello,
this is wrong :

Or even every 10 minutes
0/10 * * * * cd /var/www/<redminedir>; rake redmine:check_periodictasks RAILS_ENV="production"

should be :
*/10 * * * * cd /var/www/<redminedir>; rake redmine:check_periodictasks RAILS_ENV="production"

Max Devaine

**Comment by jperelli** [comment]
Thanks! nice catch!
