### ISSUE TITLE
Previous month and variables in description

### ISSUE THREAD

**Issue by Sledav** [jperelli/Redmine-Periodic-Task#35]
Hi!
Please add new variable **PMONTHNAME** - previous month and replacing variables in description.
I have implemented it in a file   / lib / scheduled_tasks_checker.rb 
      # replace variables (set locale from shell)
      I18n.locale = ENV['LOCALE'] || I18n.default_locale
      task.subject.gsub!('**WEEK**', Time.now.strftime("%W"))
      task.subject.gsub!('**MONTH**', Time.now.strftime("%m"))
      task.subject.gsub!('**MONTHNAME**', I18n.localize(Time.now, :format => "%B"))
      task.subject.gsub!('**YEAR**', Time.now.strftime("%Y"))
	  task.subject.gsub!('**PMONTHNAME**', I18n.localize(Time.now - 2592000, :format => "%B"))
	  task.description.gsub!('**WEEK**', Time.now.strftime("%W"))
      task.description.gsub!('**MONTH**', Time.now.strftime("%m"))
      task.description.gsub!('**MONTHNAME**', I18n.localize(Time.now, :format => "%B"))
      task.description.gsub!('**YEAR**', Time.now.strftime("%Y"))
	  task.description.gsub!('**PMONTHNAME**', I18n.localize(Time.now - 2592000, :format => "%B"))

**Comment by jperelli** [comment]
Do you want to make a pull request with this modifications? If you do that, then your name will appear as a contributor. If you don't mind, please tell me and I'll do this

**Comment by Sledav** [comment]
I don't mind, please add it

**Comment by Sledav** [comment]
It works. Everything is great!
