### ISSUE TITLE
Incorrect label

### ISSUE THREAD

**Issue by Sledav** [jperelli/Redmine-Periodic-Task#38]
There are incorrect labels in files app / views / periodictask / edit.html.erb and app / views / periodictask / new.html.erb. In file app / views / periodictask / edit.html.erb  must be written label ":label_edit_periodic_task", but not ":label_new_periodic_task". The same error in the file app / views / periodictask / new.html.erb

**Comment by jperelli** [comment]
this should be fixed now, please confirm it and the close the bug, Thanks! :)

**Comment by jperelli** [comment]
I'm closing this, as it seems to me that is fixed.
