### ISSUE TITLE
Assigning tasks to periodic task

### ISSUE THREAD

**Issue by meetdileep** [jperelli/Redmine-Periodic-Task#41]
How to assign issues also to the periodic task. Is there any way around?

Thanks in advance.

Dileep

**Comment by jperelli** [comment]
Sorry, can you please be more specific, I don't follow you. Attach an image if needed. Thanks

**Comment by jperelli** [comment]
If you mean subtasks, I think it would be too difficult and if you mean related issues then I think it could be done maybe easily, but as I don't understand you right and no one else is asking nothing like this, I'm closing this issue.

If someone can explain this better and needs a feature like this, please explain and reopen.
