### ISSUE TITLE
find_all_by_project_id not defined

### ISSUE THREAD

**Issue by fbotti** [jperelli/Redmine-Periodic-Task#45]
Installing the plugin in redmine2 we found that the method find_all_by_project_id called in plugins/periodictask/app/controllers/periodictask_controller.rb is not defned. Instead we have managed to make it function replacing this line: 

    @tasks = Periodictask.find_all_by_project_id(@project[:id])

For this one: 

    @tasks = Periodictask.where(project_id: @project)

**Comment by jperelli** [comment]
This is done in master
