### ISSUE TITLE
[Request] Add Estimated Time to Periodic Task

### ISSUE THREAD

**Issue by Landmine-1252** [jperelli/Redmine-Periodic-Task#49]
Is there a way to add the issue Estimated Time to the scheduled task page? Below Set Due Date maybe?

![image](https://cloud.githubusercontent.com/assets/16811401/17375534/34251652-5966-11e6-80d7-45ac168ec272.png)

**Comment by jperelli** [comment]
I'm doing this (sponsored by https://www.refineriaweb.com/)
