### ISSUE TITLE
periodic task configuration not understand

### ISSUE THREAD

**Issue by sachin2937** [jperelli/Redmine-Periodic-Task#51]
after add plugin on redmine, i add that module on my project.
and then it is showing as new tab like periodic task.
after then when i click on that tab when i create new task,
i dont understand how and what i need to configure on that tab.
means what is came on subject and other fields on that tab.

thanks

**Comment by jperelli** [comment]
Al the fields you cmodifyonfigure in that tab, are related with some fields of an issue (aka task) that it will be created periodically, with the periodicity you configure.
