### ISSUE TITLE
Mysql2::Error: Incorrect string value: 

### ISSUE THREAD

**Issue by radist** [jperelli/Redmine-Periodic-Task#53]
`) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 |`

`ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xD0\xA2\xD0\xB5\xD1\x81...' for column 'subject' at row 1: INSERT INTO `periodictasks` (`author_id`, `project_id`, `subject`, `assigned_to_id`, `interval_number`, `interval_units`, `tracker_id`, `set_start_date`, `due_date_units`, `description`) VALUES (4, 58, 'Тестовая задача **MONTH**', 4, 1, 'day', 3, 1, 'day', '**MONTH**')):
  plugins/periodictask/app/controllers/periodictask_controller.rb:26:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

**Comment by jperelli** [comment]
CHARSET=latin1  is not compatible with cyrillic alphabet (Тестовая задача). You need to change the charset from your database to be able to handle cyrillic. Maybe use utf-8.
