### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by te-con-miel** [jperelli/Redmine-Periodic-Task#54]
git clone http://github.com:/jperelli/Redmine-Periodic-Task.git plugins/periodictask
Cloning into 'plugins/periodictask'...
remote: Counting objects: 410, done.
remote: Total 410 (delta 0), reused 0 (delta 0), pack-reused 410
Receiving objects: 100% (410/410), 57.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (163/163), done.

/home/support/download/redmine/redmine-3.2.0/bin/rake redmine:plugins:migrate NAME=periodictask RAILS_ENV=production
Please configure your config/database.yml first
(in /var/www/redmine)
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x0000000241ac88>
/usr/local/share/gems/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:69:in `define'
/usr/local/share/gems/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:61:in `initialize'
/var/www/redmine/lib/tasks/yardoc.rake:4:in `new'
/var/www/redmine/lib/tasks/yardoc.rake:4:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/usr/local/share/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/share/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/share/gems/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/engine.rb:658:in `each'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/application.rb:452:in `run_tasks_blocks'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/engine.rb:453:in `load_tasks'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
/usr/local/share/gems/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
/var/www/redmine/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

The database.yml is already configured.

Redmine 3.2.0

Any help please?

Thanks.-

**Comment by jperelli** [comment]
Please see http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11
