### ISSUE TITLE
DAY variable

### ISSUE THREAD

**Issue by petrhasalik** [jperelli/Redmine-Periodic-Task#57]
This is what I can see when creating a new reoccuring reminder:
Possible variables are **WEEK** (01-53), **MONTH** (01-12), **MONTHNAME** (January - December), **YEAR** (YYYY)

Is there any chance to add suport for **DAY** ? I would like to add day and month into the subject.

**Comment by jperelli** [comment]
This is now fixed, please try it and tell me if it works.
