### ISSUE TITLE
[solved] migrating from an older version

### ISSUE THREAD

**Issue by ka7** [jperelli/Redmine-Periodic-Task#65]
(run into this error, started writing an issue, found the solution and document it now here )
I used periodic_task before, on a 2.1 redmine. ( https://github.com/jperelli/Redmine-Periodic-Task/tree/redmine2 )

.. Run into several issues, especially the CRON job did nor work.

` /usr/local/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production" --trace`
`** Invoke redmine:check_periodictasks (first_time)`
`** Invoke environment (first_time)`
`** Execute environment`
`** Execute redmine:check_periodictasks`
`rake aborted!`
`NoMethodError: undefined method 'issue_category_id' for #<Periodictask:0x00000008a39898>`
`/var/lib/gems/2.1.0/gems/activemodel-4.2.7.1/lib/active_model/attribute_methods.rb:433:in 'method_missing'`
`/opt/redmine/redmine-3.3.3/plugins/periodictask/lib/scheduled_tasks_checker.rb:27:in 'block in checktasks!'`
`/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in 'each'`
`/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in 'each'`

found, i had to do an upgrade of the DB-structure:

` /usr/local/bin/bundle exec rake db:migrate_plugins RAILS_ENV=production`
`(in /opt/redmine/redmine-3.3.3)`
`Migrating periodictask (Redmine Periodictask plugin)...`
`== 20151002140303 AddCategoryToPeriodictasks: migrating =======================`
`-- add_column(:periodictasks, :issue_category_id, :integer, {:null=>true, :default=>nil})`
`   -> 0.0951s`
`== 20151002140303 AddCategoryToPeriodictasks: migrated (0.0954s) ==============`

**Comment by jperelli** [comment]
This is documented on README.md as this command

    bundle exec rake redmine:plugins:migrate NAME=periodictask RAILS_ENV=production

I'm not sure of why/when this differences should be noted

    db:migrate_plugins      <--- the command you used
    redmine:plugins:migrate  <--- the one that is documented

This needs to be documented. Do you know the reason of this difference? Is this because of a redmine version?
