### ISSUE TITLE
Periodic task not working if field next run date was left empty

### ISSUE THREAD

**Issue by riedmueller** [jperelli/Redmine-Periodic-Task#68]
Cronjob is working hourly.  Already tested on other tasks and it was OK. But if i make a task  with empty next run field it seems to start never!?
As seen in the table the data points to "NULL". My expectation was that in this case the first task was set in the next hour (because of hourly cronjob). But nothing happens. 

Data out of mysql db table periodictask:
| id | project_id | tracker_id | assigned_to_id | author_id | subject                   | interval_number | interval_units | last_assigned_date | next_run_date | set_start_date | due_date_number | due_date_units | description                            | issue_category_id |
|  1 |          5 |          2 |              7 |         7 | test **DAY** |               1 | day            | NULL               | NULL          |              1 |               1 | week           | sfdgfdsg |              NULL |

So what's the failure?
Thanks!

**Comment by jperelli** [comment]
@riedmueller fixed in latest v5.0.0
