### ISSUE TITLE
clicking "period task" menu gives Page not found

### ISSUE THREAD

**Issue by joeribelis** [jperelli/Redmine-Periodic-Task#73]
I installed periodictask 3.2.1 on 
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

But when i activate it on a project and i click on the menu periodic task it takes me to an url that does not exists

Page not found
The page you were trying to access doesn't exist or has been removed.
Back

What am i doing wrong?

**Comment by walcher** [comment]
Hi!

You have to check the plugin folder is named periodictask

**Comment by jperelli** [comment]
@walcher correct.
