### ISSUE TITLE
not automatically creates issues 

### ISSUE THREAD

**Issue by Ryoferdn** [jperelli/Redmine-Periodic-Task#78]
Hello,
in redmine 3.3.0.stable not automatically creates issues with environment: 

 Redmine version                3.3.0.stable
 Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
 Rails version                  4.2.6
 Environment                    production 
 Database adapter               Mysql2
,possibly problem with version ruby?

thanks

**Comment by Druid33** [comment]
Hi,
i have same problem.

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.5
  clipboard_image_paste          1.12
  periodictask                   3.2.1
  plantuml                       0.3.0
  redmine_agile                  1.4.2
  redmine_checklists             3.1.5
  redmine_editor_preview_tab     0.1.5
  redmine_issue_badge            0.0.6
  redmine_issue_dynamic_edit     0.6.3
  redmine_lightbox2              0.3.5
  redmine_my_page_queries        2.0.7
  redmine_preview_attach_column  0.1.7
  redmine_reports                0.0.1
  redmine_stats                  0.0.1
  redmine_wiki_extensions        0.7.0
  usability                      2.2.6

**Comment by njdattler** [comment]
Same issue here:

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.13
  periodictask                   3.3.1
  redmine_agile                  1.4.7
  redmine_auto_assign_group      0.1.0
  redmine_checklists             3.1.11
  redmine_documents              1.0.0
  redmine_issue_history          1.0.0
  redmine_knowledgebase          3.3.1
  redmine_local_avatars          1.0.3
  redmine_my_page                0.1.13
  redmine_report_filters         1.2.4
  redmine_stats                  0.0.3
  time_logger                    0.5.4

**Comment by njdattler** [comment]
I notice the following lines when running the rake task that's within crontab manually:

/home/redmine/redmine3-4-4_setup/redmine-3.4.4/plugins/periodictask/lib/scheduled_tasks_checker.rb:58:in `block in checktasks!'

/home/redmine/redmine3-4-4_setup/redmine-3.4.4/plugins/periodictask/lib/scheduled_tasks_checker.rb:4:in `checktasks!'

/home/redmine/redmine3-4-4_setup/redmine-3.4.4/plugins/periodictask/lib/tasks/periodictask.rake:11:in `block (2 levels) in <top (required)>'

**Comment by njdattler** [comment]
I actually found a different plugin that worked as expected. I do appreciate your help howevrer.

**Comment by jperelli** [comment]
@njdattler I think that @yzzy was saying that maybe another plugin interferes with redmine-periodic-task, and maybe this one fails only because the other one is installed. Can you tell us what other plugins do you have installed?

**Comment by yzzy** [comment]
@jperelli 
@njdattler already tells which plugins he had. I think `redmine_agile` causes this, but can't check right now

**Comment by njdattler** [comment]
I ended up using  different plugin, but I do appreciate the feedback.

**Comment by jan-imrich** [comment]
We are currently experiencing similar issue. The cron command executes without any error, but the issue is not created.
There is only this warning in redmine log:
`W, [2020-12-14T11:52:15.215261 #1]  WARN -- : WARNING: Can't mass-assign protected attributes for Periodictask: id
	plugins/periodictask/app/controllers/periodictask_controller.rb:52:in `update'
	lib/redmine/sudo_mode.rb:65:in `sudo_mode'
	plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'
`

Our environment: 
`Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
  GitMirror                      2.20.1
Redmine plugins:
  additionals                    3.0.0
  periodictask                   4.1.0
  redmine_autoclose              0.0.4
  redmine_checklists             3.1.18
  redmine_dmsf                   2.4.4
  redmine_git_mirror             0.8.0
  redmine_pivot_table            0.0.7
  sidebar_hide                   0.0.8
  stopwatch                      0.1.0
  stuff_to_do_plugin             0.7.1
  vault                          0.4.1`

**Comment by Benoit-KARCI** [comment]
Same problem here with environnement :

Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  periodictask                   4.1.0
  redmine_checklists             3.1.18
  redmine_custom_workflows       1.0.4
  redmine_mentions               0.1.1
  scrum                          0.20.0


I noticed that we all have only one plugin in common :  redmine_checklists.
So if there's a conflict with another plugin, it could be this one. Can someone investigate on this? Sadly I can't do it myself...

**Comment by yzzy** [comment]
@Benoit-KARCI 
Sorry can't confirm on a fresh Redmine install with only `periodictask` and `redmine_checklists` plugins.
Was the next run date changed after running `rake` task?
Do you have some custom fields defined on `Issues`? Are some of them *required*?

**Comment by Benoit-KARCI** [comment]
> @Benoit-KARCI
> Sorry can't confirm on a fresh Redmine install with only `periodictask` and `redmine_checklists` plugins.
> Was the next run date changed after running `rake` task?
> Do you have some custom fields defined on `Issues`? Are some of them _required_?
@yzzy 
The run date didn't changed indeed and no Issue have been created. So it's like it's don't even running.
I have 3 custom fields on Issues but none of them are required.

**Comment by yzzy** [comment]
Can you replace `REDMINE_ROOT/plugins/periodictask/lib/scheduled_tasks_checker.rb` with this one (you need to change file extension to .rb)
[scheduled_tasks_checker.txt](https://github.com/jperelli/Redmine-Periodic-Task/files/5924741/scheduled_tasks_checker.txt)
Then restart your `Redmine`, run `rake` task and look the `production.log` for a line
```
ScheduledTaskChecker: X tasks to be done
```

**Comment by volcom** [comment]
We have the same problem:
`
WARNING: Can't mass-assign protected attributes for Periodictask: id
        plugins/periodictask/app/controllers/periodictask_controller.rb:52:in `update'
        lib/redmine/sudo_mode.rb:65:in `sudo_mode'
Redirected to http://192.168.64.242/projects/fal-hscerp/periodictask
`


`Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  periodictask                   4.1.0`

I replaced the scheduled_tasks_checker.rb content withe the content from the txt.
Nothing happens, log does not show the line it should, also the issues wasn't created.

**Comment by jperelli** [comment]
Please try latest version(v5.0.0) and reopen if you still have the issue
