### ISSUE TITLE
DB fields not set

### ISSUE THREAD

**Issue by samir-plusb** [jperelli/Redmine-Periodic-Task#8]
Hi,

I installed this plugin and there were no errors during installation. 

Unfortunately it is not working. The Database fields 'next_run_date' and 'last_assigned_date' are not set after creating a recurring Task. I have no experience in ruby development. Is there anything I can do to fix this?

Environment Details
  Redmine version: 2.3.1.stable.11966
  Ruby version: 1.8.7 (x86_64-linux)
  Rails version: 3.2.13
  Environment: production
  Database adapter: Mysql2

**Comment by jperelli** [comment]
Closing this issue as it is too old (2 years), the plugin has evolved a lot, and no other user had the same complain.
