### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by opozd** [jperelli/Redmine-Periodic-Task#85]
Hello!

I try to create a periodic task, but I get an error.
"Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error."

Here is the content from the log file:
Processing by PeriodictaskController#index as HTML
  Parameters: {"project_id"=>"test2"}
  Current user: opoz (id=5)
  Rendered plugins/periodictask/app/views/periodictask/index.html.erb within layouts/base (3.1ms)
  Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (1.4ms)
  Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.5ms)
Completed 200 OK in 88ms (Views: 59.4ms | ActiveRecord: 11.8ms)
Started GET "/projects/test2/periodictask/new" for 192.168.1.33 at 2018-09-21 23:49:46 +0300
Processing by PeriodictaskController#new as HTML
  Parameters: {"project_id"=>"test2"}
  Current user: opoz (id=5)
WARNING: Can't mass-assign protected attributes for Periodictask: project
        plugins/periodictask/app/controllers/periodictask_controller.rb:19:in `new'
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  Rendered plugins/periodictask/app/views/periodictask/_form.html.erb (26.5ms)
  Rendered plugins/periodictask/app/views/periodictask/new.html.erb within layouts/base (27.9ms)
Completed 500 Internal Server Error in 55ms (ActiveRecord: 8.2ms)

ActionView::Template::Error (uninitialized constant PeriodictaskHelper::ChecklistTemplate):
    39:   <% if checklistPluginInstalled? %>
    40:     <p>
    41:       <%= label(:periodictask, :checklists_template_id, l(:label_checklist_template)) %>
    42:       <%= select :periodictask, :checklists_template_id, template_options_for_select(@project, f.object.checklists_template_i$
    43:     </p>
    44:   <% end %>
    45: </div>
  plugins/periodictask/app/helpers/periodictask_helper.rb:8:in `template_options_for_select'
  plugins/periodictask/app/views/periodictask/_form.html.erb:42:in `_plugins_periodictask_app_views_periodictask__form_html_erb___198$
  plugins/periodictask/app/views/periodictask/new.html.erb:4:in `block in _plugins_periodictask_app_views_periodictask_new_html_erb__$
  plugins/periodictask/app/views/periodictask/new.html.erb:3:in `_plugins_periodictask_app_views_periodictask_new_html_erb___43143307$
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I have more plugins: tags and checklist https://www.redmineup.com/pages/plugins/checklists

**Comment by opozd** [comment]
Hi! 
Environment:
  Redmine version                3.4.6.stable.17480
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  periodictask                   3.3.0
  redmine_checklists             3.1.11
  redmineup_tags                 2.0.3

https://www.redmineup.com/pages/plugins/checklists  - Litght version.

Thank you.

**Comment by jperelli** [comment]
Ok, fixed by @yzzy was merged and a release has been made (v3.3.1)
