### ISSUE TITLE
how to add "Periodic Task" tab in project manager's page

### ISSUE THREAD

**Issue by zuoliang365** [jperelli/Redmine-Periodic-Task#93]
Thanks for your greate work.
I found that there are no new tab named "Periodic Task" in project manager role's page.
But it appares in admin's page.
Is there a way to allow project manager to config Periodic Task?
Thanks a lot!

**Comment by yzzy** [comment]
@zuoliang365 
Did you set `Periodictask` permission for manager role on `Roles and permissions` page in `Administration` settings? That shoud be enough.

See bottom of the picture:
![image](https://user-images.githubusercontent.com/390303/53008813-02325780-345c-11e9-8e6a-0e7d2020aa6c.png)

**Comment by jperelli** [comment]
seems solved to me, please reopen if necessary
