### ISSUE TITLE
Error 404: uninitialized constant PeriodictaskController

### ISSUE THREAD

**Issue by bakanyaka** [jperelli/Redmine-Periodic-Task#94]
Hello. I'm getting 404 uninitialized constant PeriodictaskController error. When i try to visit project's "Periodic task" page (http://redmine.url/projects/project_name/periodictask). 
**Environment:**
> Redmine version                3.4.8.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.0
  custom_menu                    1.8.5
  extra_queries                  2.3.5
  global_roles                   2.2.3
  periodictask                   3.3.1
  redmine_checklists             3.1.5
  redmine_contacts               4.2.3
  redmine_issue_tabs             1.3.1
  redmine_lightbox2              0.4.4
  redmine_people                 1.4.0
  redmine_send_issue_reply_email 1.0.0
  usability                      2.3.8

**Error log:**
> /usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:261:in `const_get'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:259:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:259:in `inject'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:259:in `constantize'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:60:in `controller'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:39:in `serve'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/content_length.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/application.rb:165:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `method_missing'
/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by yzzy** [comment]
@bakanyaka 
can you try to run your Redmine without Passenger layer, directly `rails server` from REDMINE_ROOT?

**Comment by bakanyaka** [comment]
Same error while running directly :
uninitialized constant PeriodictaskController 

> /usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:261:in `const_get'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:259:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:259:in `inject'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/inflector/methods.rb:259:in `constantize'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:60:in `controller'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:39:in `serve'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/content_length.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-4.2.11/lib/rails/application.rb:165:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/lock.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/content_length.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.3.4/gems/rack-1.6.11/lib/rack/handler/webrick.rb:88:in `service'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**Comment by yzzy** [comment]
@bakanyaka 
Please make sure that plugin is installed under `#{REDMINE_ROOT}/plugins/periodictask` directory
File `periodictask_controller.rb` should be in `#{REDMINE_ROOT}/plugins/periodictask/app/controllers/` directory

**Comment by bakanyaka** [comment]
> @bakanyaka
> Please make sure that plugin is installed under `#{REDMINE_ROOT}/plugins/periodictask` directory

Thank you. My bad. My plugin folder was called periodic_task. Renamed it, run migrations again (had missing table error) and now it works.
