### ISSUE TITLE
Plugin doesn't initialize DB

### ISSUE THREAD

**Issue by mcbglug** [jperelli/Redmine-Periodic-Task#97]
Hi the plugin is installed correctly but it doesn't create the table periodictask in DB when i try to enable the plugin in my project everything is OK, but when i try to access to the plugin url i receive
"Page not found

The page you were trying to access doesn't exist or has been removed."

I use redmine 4.0.4 and periodicplugin 4.1.

In redmine log i find :
Started GET "/projects/neotech/periodictask" for 127.0.0.1 at 2019-09-05 18:03:28 +0200
  
ActionController::RoutingError (uninitialized constant PeriodictaskController):
  
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:283:in `const_get'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:283:in `block in constantize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:281:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:281:in `inject'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/inflector/methods.rb:281:in `constantize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:582:in `get'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:613:in `constantize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/http/request.rb:88:in `controller_class_for'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/http/request.rb:81:in `controller_class'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:46:in `controller'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/content_length.rb:15:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:605:in `process_client'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:700:in `worker_loop'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:144:in `start'
vendor/bundle/ruby/2.4.0/gems/unicorn-5.5.1/bin/unicorn_rails:209:in `<top (required)>'

Bye

**Comment by mcbglug** [comment]
Hi i created the DB tables manually, but now when i create a new periodical task in redmine production log  i found:

NameError (undefined local variable or method `custom_field_values' for #<Periodictask:0x0000000004efdd60>):
  
plugins/periodictask/app/models/periodictask.rb:92:in `fill_custom_fields'
plugins/periodictask/app/models/periodictask.rb:56:in `generate_issue'
plugins/periodictask/app/controllers/periodictask_controller.rb:26:in `new'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by x-itec** [comment]
+1 Same here

**Comment by yzzy** [comment]
I can't confirm this behavior on a fresh `Redmine 4.0.4` and `periodictask 4.1`
Please ensure that plugin source is on `#{REDMINE_ROOT}/plugins/periodictask`

**Comment by mcbglug** [comment]
> I can't confirm this behavior on a fresh `Redmine 4.0.4` and `periodictask 4.1`
> Please ensure that plugin source is on `#{REDMINE_ROOT}/plugins/periodictask`
Your're right i uninstalled the plugin, removed the table, and reinstalled everything and now works.

Thanks

**Comment by x-itec** [comment]
Stop - I just checked out the plugin without renaming it -((( Now it seems to work (OS: Windows 10).  This is the only plugin I have to rename after downloading - sorry 
Thx

**Comment by yzzy** [comment]
Just use `git clone` as described in `README`

**Comment by jperelli** [comment]
Ok, thanks @x-itec for sharing the solution
