### ISSUE TITLE
/usr/bin/env: ruby_executable_hooks: No such file or directory

### ISSUE THREAD

**Issue by mihainicu** [jperelli/Redmine-Periodic-Task#99]
Hi, 

We have redmine Redmine 4.0.4.devel and I used your plugin to configure periodic tasks but when they are being executed via cron I receive this message:

/usr/bin/env: ruby_executable_hooks: No such file or directory

Can you point me in the right direction?

**Comment by yzzy** [comment]
Please provide your `crontab` line

**Comment by mihainicu** [comment]
Hi, 
this is it: 
* * * * * cd /home/redmine; /home/redmine/gems/ruby-2.6.3/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production"

**Comment by yzzy** [comment]
Replace `bin` in the `bundle` `path` with `wrappers`
```
/home/redmine/gems/ruby-2.6.3/wrappers/bundle exec rake redmine:check_periodictasks RAILS_ENV="production"
```

**Comment by mihainicu** [comment]
That did the job! much appreciated

**Comment by tinti** [comment]
> Replace `bin` in the `bundle` `path` with `wrappers`
> 
> ```
> /home/redmine/gems/ruby-2.6.3/wrappers/bundle exec rake redmine:check_periodictasks RAILS_ENV="production"
> ```

Solved my problem.
